export const webhooksData = [
  {
    name: "Сделки",
    data: {
      "type": "Deal",
      "timestamp": 1519466985,
      "data": {
        "id": 72738,
        "name": "Сделка",
        "description": null,
        "note": null,
        "amount": "0.0",
        "cost": "0.0",
        "finished_at": null,
        "planned_at": null,
        "created_at": "02.02.2018 18:36:41",
        "updated_at": "02.02.2018 18:36:41",
        "invoice_ids": [],
        "product_ids": [],
        "entities_product_ids": [],
        "user_id": 1,
        "user": "Andreeeee",
        "responsible_id": 1,
        "responsible": "Andreeeee",
        "stage_id": 1129,
        "stage": "База для обзвона",
        "stage_category_id": 150,
        "stage_category": "Партнеры",
        "status_id": 65,
        "status": "Без статуса",
        "source_id": null,
        "source": "",
        "area_id": null,
        "area": "",
        "loss_reason_id": null,
        "loss_reason": "",
        "loss_competitor_id": null,
        "loss_competitor": "",
        "company_id": null,
        "company": "",
        "contact_id": null,
        "contact": "",
        "custom_5808": [],
        "custom_10535": [],
        "custom_11906": []
      },
      "custom_fields": {
        "custom_5808": "Маркерt",
        "custom_10535": "Куратор ФГ",
        "custom_11906": "Тариф"
      }
    }
  },
  {
    name: "Заявки",
    data: {
      "type": "Order",
      "timestamp": 1519556577,
      "data": {
        "id": 45797,
        "name": "Api test",
        "description": "Api test v 0.1",
        "note": null,
        "amount": "0.0",
        "cost": "0.0",
        "created_at": "04.10.2017 19:06:01",
        "updated_at": "04.10.2017 19:06:01",
        "user_id": 1,
        "user": "Andreeeee",
        "responsible_id": null,
        "responsible": "",
        "stage_id": 127,
        "stage": "Не обработана",
        "stage_category": "",
        "stage_category_id": null,
        "status_id": 45,
        "status": "Без статуса",
        "source_id": null,
        "source": "",
        "area": "",
        "area_id": null,
        "loss_reason_id": null,
        "loss_reason": "",
        "loss_competitor_id": null,
        "loss_competitor": "",
        "company_id": null,
        "company": "",
        "contact_id": null,
        "contact": "",
        "custom_26": "",
        "custom_27": "",
        "custom_130": "",
        "custom_12239": []
      },
      "custom_fields": {
        "custom_26": "Сообщение",
        "custom_27": "Комп. (партнер)",
        "custom_130": "Интересно",
        "custom_12239": "Куратор ФГ"
      }
    }
  },
  {
    name: "Компании",
    data:
    {
      "type": "Company",
      "timestamp": 1519556956,
      "data": {
        "id": 43534,
        "name": "Conroy-Parker",
        "general_phone": null,
        "work_phone": "+79001231212",
        "other_phone": "+79001231212",
        "fax": null,
        "email": "e@ma.il",
        "other_email": "email@mail.com",
        "website": "google.com",
        "description": null,
        "note": null,
        "inn": null,
        "full_name": null,
        "short_name": null,
        "ogrn": null,
        "kpp": null,
        "okved": null,
        "okpo": null,
        "manager_name": null,
        "manager_position": null,
        "lawfulness_base": null,
        "accountant": null,
        "country": null,
        "address": "5th Avenue",
        "region": "NY",
        "city": "NY, Manhattan",
        "street": null,
        "house": null,
        "flat": null,
        "zip_code": "37891-0000",
        "juristic_country": null,
        "juristic_region": null,
        "juristic_city": null,
        "juristic_zip_code": null,
        "juristic_street": null,
        "juristic_house": null,
        "juristic_build": null,
        "juristic_office": null,
        "actual_country": null,
        "actual_region": null,
        "actual_city": null,
        "actual_zip_code": null,
        "actual_street": null,
        "actual_house": null,
        "actual_build": null,
        "actual_office": null,
        "mailing_country": null,
        "mailing_region": null,
        "mailing_city": null,
        "mailing_zip_code": null,
        "mailing_street": null,
        "mailing_house": null,
        "mailing_build": null,
        "mailing_office": null,
        "created_at": "26.12.2017 10:30:56",
        "updated_at": "26.12.2017 10:30:56",
        "user_id": 5851,
        "user": "Светочка",
        "responsible_id": null,
        "responsible": "",
        "source_id": null,
        "source": "",
        "status_id": null,
        "status": "",
        "type_id": null,
        "type": "",
        "custom_1": "Только наличными"
      },
      "custom_fields": {
        "custom_1": "Особые отметки"
      }
    }
  },

  {
    name: "Контакты",
    data: {
      "type": "Contact",
      "timestamp": 1519557678,
      "data": {
        "id": 54654,
        "name": "Lastname Firstname Middlename",
        "position": "lll",
        "first_name": "Firstname",
        "last_name": "Lastname",
        "middle_name": "Middlename",
        "mobile_phone": null,
        "general_phone": null,
        "work_phone": null,
        "other_phone": null,
        "email": "llll@llll.lll",
        "other_email": null,
        "description": "basic",
        "note": null,
        "fax": null,
        "website": null,
        "created_at": "27.12.2017 10:00:11",
        "updated_at": "27.12.2017 10:00:11",
        "work_country": null,
        "work_region": null,
        "work_city": null,
        "work_zipcode": null,
        "work_street": null,
        "work_building": null,
        "work_housing": null,
        "work_apartment": null,
        "home_country": null,
        "home_region": null,
        "home_city": null,
        "home_zipcode": null,
        "home_street": null,
        "home_building": null,
        "home_housing": null,
        "home_apartment": null,
        "vkontakte": null,
        "facebook": null,
        "linkedin": null,
        "odnoklassniki": null,
        "instagram": null,
        "twitter": null,
        "whatsapp": null,
        "viber": null,
        "telegram": null,
        "skype": null,
        "responsible_id": 2,
        "responsible": "Яковлевски Эндрю",
        "user_id": 2,
        "user": "Яковлевски Эндрю",
        "status_id": null,
        "status": "",
        "type_id": 19975,
        "type": "Регистрация",
        "source_id": null,
        "source": ""
      },
      "custom_fields": {}
    }
  },

  {
    name: "Почтовые сообщения",
    data: {
      "type": "MailMessage",
      "timestamp": 1519557828,
      "data": {
        "from": [
          {
            "name": "Андрей Спамер",
            "address": "spam@yandex.ru"
          }
        ],
        "to": [
          {
            "name": null,
            "address": "retired@person.ru"
          }
        ],
        "subject": "Просто заберите ваши деньги",
        "message_id": "<00000000000000@web52g.yandex.ru>",
        "body": "<div>Здравствуйте!</div><br /><span lang=\"ru\">Вы выиграли лярд!</span>",
        "direction": "outgoing",
        "replied_at": null,
        "forwarded_at": null,
        "created_at": "04.09.2017 15:14:38",
        "folder_id": 3193,
        "folder": "Отправленные",
        "label_id": null,
        "label": "",
        "responsible_id": null,
        "responsible": "",
        "creator_id": 3136,
        "creator": "Андрей Спамер"
      }
    }
  },

  {
    name: "Телефонные звонки",
    data: {
      "type": "TelephonyCall",
      "data": {
        "id": 5709232,
        "direction": "outgoing",
        "call_id": "out_a07d018ea75be3b71087e99072b43497f5fe7342",
        "dst_phone_number": "+79998887777",
        "src_phone_number": "122",
        "number": 112653,
        "tech_code": null,
        "duration": null,
        "started_at": "30.10.2019 10:40:44",
        "answered_at": null,
        "completed_at": null,
        "created_at": "30.10.2019 10:40:44",
        "updated_at": "30.10.2019 10:40:44",
        "status_id": 9510,
        "status": "Неотвечено",
        "custom_42199": null,
        "custom_48153": [],
        "custom_42198": null
      },
      "timestamp": 1572421245
    }
  },
  {
    name: "Визиты",
    data: {
      "type": "Checkup",
      "data": {
        "id": 5709232,
        "number": 18,
        "name": "Визит",
        "description": "<p>тут должно быть ваше описание визита</p>",
        "planned_at": "2020-10-08 13:15:00",
        "created_at": "2021-02-17 13:01:31",
        "updated_at": "2021-02-17 13:01:48",
        "contact_id": null,
        "contact": "",
        "user_id": 82,
        "user": "Вострецова Олеся",
        "custom_34565": null,
        "custom_34566": []
      },
      "timestamp": 1572421245
    }
  },

  {
    name: "Задачи",
    data: {
      "type": "Diary",
      "data": {
        "id": 435646,
        "name": "Задача",
        "description": "<p>тут должно быть ваше описание задачи</p>",
        "note": "Заметка по задаче",
        "completed_at": "2022-09-24 19:01:31",
        "due_date": "2022-09-24 19:01:31",
        "user": "Вострецова Олеся",
        "user_id": 82,
        "responsible": "Вострецова Олеся",
        "responsible_id": 82,
        "type": "DiaryTask",
        "priority": null,
        "company": "ООО Рога и копыта",
        "company_id": 12,
        "contact": "Иванов Иван Иванович",
        "contact_id": 13,
        "deal": "Сделка",
        "deal_id": 14,
        "order": "Заявка",
        "order_id": 15,
        "estate_property": null,
        "estate_property_id": null,
        "product": null,
        "product_id": null,
        "labels": [],
        "custom_34567": null,
        "custom_34568": []
      },
      "timestamp": 1572421245
    }
  },

  {
    name: "Записи",
    data: {
      "type": "Entry",
      "data": {
        "id": 435646,
        "name": "Запись",
        "comment": "<p>комментарий к записи</p>",
        "start_time": "2022-09-24 13:01:31",
        "end_time": "2022-09-24 15:01:31",
        "created_at": "2021-02-17 13:01:31",
        "updated_at": "2021-02-17 13:01:48",
        "creator": "Иванов Иван Иванович",
        "creator_id": 1,
        "responsible": "Иванов Иван Иванович",
        "responsible_id": 1,
        "status": "Просрочено",
        "status_id": 2,
        "service": "",
        "service_id": null,
        "source": "",
        "source_id": null,
        "calendar": "",
        "calendar_id": null,
        "contacts": [],
        "companies": [],
        "custom_34571": null,
        "custom_34572": []
      },
      "timestamp": 1572421245
    }
  },
  {
    name: "Объекты недвижимости",
    data: {
      "type": "EstateProperty",
      "data": {
        "id": 435646,
        "name": "2 комн. кв., 56.0 м², 3/5 этаж",
        "description": "<p>комментарий к объекту недвижимости</p>",
        "purchase_price": 12000000,
        "uid": "46a07d018ea75be3b71087e99072b43497f5fe7342",
        "railway": null,
        "cadastral_num": null,
        "highway_name": null,
        "subway_name": null,
        "address": "Степана Разина 72",
        "country": "Российская Федерация",
        "region": "Самарская область",
        "locality": null,
        "district": null,
        "building_name": null,
        "build_at": null,
        "city_dist": null,
        "subway_dist": null,
        "subway_transport": null,
        "subway_foot": null,
        "room_number": null,
        "total_room": null,
        "separate_rooms": null,
        "rooms_for_sell": null,
        "floor_number": null,
        "total_floors": null,
        "deal_category": null,
        "deal_type": null,
        "object_category": null,
        "object_type": null,
        "installments": null,
        "bargain": null,
        "mortgage": null,
        "balcony": null,
        "building_class": null,
        "building_type": null,
        "business_usage_type": null,
        "commission_type": null,
        "condition": null,
        "climate": null,
        "currency": null,
        "feature": null,
        "electricity": null,
        "flat_status": null,
        "flat_type": null,
        "gas": null,
        "gate": null,
        "heating": null,
        "highway_access": null,
        "land_usage_type": null,
        "layout": null,
        "material": null,
        "new_flat": null,
        "ownership": null,
        "parking_type": null,
        "rent_period": null,
        "plumbing": null,
        "payment_period": null,
        "land_purpose": null,
        "ready_quarter": null,
        "relief": null,
        "renovation": null,
        "sewerage": null,
        "storage_type": null,
        "toilet": null,
        "warehouse_floor": null,
        "warehouse_type": null,
        "location_type": null,
        "window_view": null,
        "encumbrance": null,
        "build_stage": null,
        "rent_deposit": null,
        "ceiling_height": null,
        "longitude": null,
        "latitude": null,
        "land_area": null,
        "total_area": null,
        "living_area": null,
        "kitchen_area": null,
        "commission_sum": null,
        "contact_phone": null,
        "map_url": null,
        "created_at": "2021-02-17 13:01:31",
        "updated_at": "2021-02-17 13:01:31",
        "burden": null,
        "stories": null,
        "garage_type": null,
        "parking_lot_type": null,
        "shape": null,
        "house_number": null,
        "flat_house_type": null,
        "images": [],
        "user": "Иванов Иван Иванович",
        "user_id": 1,
        "responsible": "Иванов Иван Иванович",
        "responsible_id": 1,
        "status": "",
        "status_id": null,
        "source": "",
        "source_id": null,
        "image": "",
        "image_id": null,
        "company": "",
        "company_id": null,
        "contact": "",
        "contact_id": null,
        "custom_34569": null,
        "custom_34570": []
      },
      "timestamp": 1572421245
    }
  },

  {
    name: "Счета",
    data: {
      "type": "Invoice",
      "data": {
        "id": 54654,
        "number": 1,
        "custom_number": "number-1",
        "vat_kind": "without",
        "vat_rate": 13,
        "vat_by_line": false,
        "reason": "",
        "payer_type": "Contact",
        "prefix": null,
        "postfix": null,
        "amount": 1000,
        "paid_amount": null,
        "balance": 1000,
        "due_date": "2022-09-24 13:01:31",
        "issued_at": "2022-09-24 13:01:31",
        "status": "",
        "status_id": null,
        "created_at": null,
        "updated_at": null,
        "user": null,
        "user_id": null,
        "responsible": null,
        "responsible_id": null,
        "payer": null,
        "payer_id": null,
        "entry": null,
        "entry_id": null,
        "deal": null,
        "deal_id": null,
        "order": null,
        "order_id": null,
        "account_bank_detail": null,
        "account_bank_detail_id": null,
        "company_bank_detail": null,
        "company_bank_detail_id": null,
        "positions": [],
        "custom_34569": null,
        "custom_34570": []
      },
      "timestamp": 1572421245
    }
  },
  {
    name: "Платежи",
    data: {
      "type": "InvoicePayment",
      "data": {
        "id": 23434,
        "purpose": "",
        "amount": 1000,
        "operation_created_at": "2022-09-24 13:01:31",
        "operation_accounted_at": "2022-09-24 13:01:31",
        "operation_executed_at": "2022-09-24 13:01:31",
        "description": "",
        "direction": "income",
        "custom_number": "number-2",
        "status": "",
        "payment_type": null,
        "user": "Иванов Иван Иванович",
        "user_id": 2,
        "responsible": "Иванов Иван Иванович",
        "responsible_id": 2,
        "invoice": "",
        "invoice_id": null,
        "payer": "",
        "payer_id": null,
        "payer_bank_detail": "",
        "payer_bank_detail_id": null,
        "receiver": "",
        "receiver_id": null,
        "receiver_bank_detail": "",
        "receiver_bank_detail_id": null,
        "invoice_payment_category": "",
        "invoice_payment_category_id": null,
        "deal": "",
        "deal_id": null,
        "order": "",
        "order_id": null,
        "entry": "",
        "entry_id": null,
        "contract": "",
        "contract_id": null,
        "business_type": "",
        "business_type_id": null,
        "custom_34573": null,
        "custom_34574": []
      },
      "timestamp": 567457457547
    }
  },
  {
    name: "Позиции",
    data: {
      "type": "InvoicePosition",
      "data": {
        "id": 8765,
        "name": "Сетевой фильтр",
        "quantity": 2,
        "amount": 1000,
        "amount_with_discount": 900,
        "amount_by_quantity": 2000,
        "unit": "шт",
        "is_service": false,
        "product_id": 1,
        "product": "Сетевой фильтр",
        "code": 43534,
        "discount": 10,
        "discount_amount": 100,
        "result_vat": null,
        "created_at": "2022-09-24 13:01:31",
        "updated_at": "2022-09-24 13:01:31"
      },
      "timestamp": 2142424434
    }
  },
  {
    name: "Продукты",
    data: {
      "type": "Product",
      "data": {
        "id": 8765,
        "name": "Сетевой фильтр",
        "description": "",
        "is_service": false,
        "kind": 0,
        "created_at": "2022-09-24 13:01:31",
        "updated_at": "2022-09-24 13:01:31",
        "code": 546546,
        "vendor_code": 34234,
        "purchase_price": 0,
        "cost_price": 0,
        "document_id": null,
        "document": "",
        "duration": null,
        "selling_price": 0,
        "vat": 0,
        "volume": null,
        "weight": null,
        "ccd": null,
        "country": null,
        "number": 436,
        "exchange_rate": null,
        "currency_id": null,
        "currency": "",
        "spending_price": null,
        "available_quantity": null,
        "stock_quantity": null,
        "reserved_quantity": null,
        "waiting_quantity": null,
        "country_code": null,
        "parent_id": null,
        "parent": "",
        "type": null,
        "discount": null,
        "status": null,
        "unit": null,
        "category": null
      },
      "timestamp": 234235423
    }
  },
  {
    name: "Вложенные продукты",
    data: {
      "type": "EntityProduct",
      "data": {
        "id": 657567,
        "product_id": 1,
        "product": "Розетка",
        "quantity": 2,
        "purchase_price": 0,
        "description": "",
        "created_at": "2022-09-24 13:01:31",
        "updated_at": "2022-09-24 13:01:31",
        "duration": null,
        "selling_price": 1000,
        "cost_price": 0,
        "discount": 10,
        "exchange_rate": null,
        "currency_id": 3,
        "currency": "руб.",
        "spending_price": 0,
        "vat": null,
        "promocode_ids": [],
        "unit": "шт",
        "status": ""
      },
      "timestamp": 6785685685
    }
  },
  {
    name: "Сотрудники",
    data: {
      "type": "User",
      "data": {
        "id": 34534,
        "email": "test@test.ru",
        "phone": "89999999999",
        "first_name": "Иван",
        "last_name": "Иванов",
        "middle_name": "Иванович",
        "work_position": "Управляющий"
      },
      "timestamp": 567567567
    }
  },
  {
    name: "Договоры",
    data: {
      "type": "Contract",
      "data": {
        "id": 1,
        "number": 1,
        "name": "Договор 1",
        "date": "05.10.2022",
        "custom_number": "1",
        "created_at": "04.10.2022 13:20:16",
        "updated_at": "18.10.2022 14:19:48",
        "products_amount": "22000.0",
        "user_id": 6,
        "user": "Иван Иванов",
        "responsible_id": 6,
        "responsible": "Иван Иванов",
        "first_party_type": "Contact",
        "first_party_id": 2,
        "first_party": "Алексей",
        "second_party_type": "Contact",
        "second_party_id": 8,
        "second_party": "Не указано"
      },
      "timestamp": 1666091989
    }
  }
]